import { DEFAULT_UPDATE_MANIFEST_URL } from "./constants";

declare const __INSTAGRAM_INSIGHTS_CLI_VERSION__: string;
declare const __INSTAGRAM_INSIGHTS_UPDATE_MANIFEST_URL__: string;

export const EMBEDDED_CLI_VERSION =
  typeof __INSTAGRAM_INSIGHTS_CLI_VERSION__ !== "undefined"
    ? __INSTAGRAM_INSIGHTS_CLI_VERSION__
    : process.env.INSTAGRAM_INSIGHTS_EMBEDDED_VERSION ?? "1.0.0";

export const EMBEDDED_UPDATE_MANIFEST_URL =
  typeof __INSTAGRAM_INSIGHTS_UPDATE_MANIFEST_URL__ !== "undefined"
    ? __INSTAGRAM_INSIGHTS_UPDATE_MANIFEST_URL__
    : process.env.INSTAGRAM_INSIGHTS_EMBEDDED_UPDATE_MANIFEST_URL ??
      DEFAULT_UPDATE_MANIFEST_URL;
