import type {
  InstagramMediaListItem,
  LinkedInstagramAccountSummary,
  PrecomputedAnalysisReport,
  ReportResponse,
} from "./types";

export function makeFixtureAccount(): LinkedInstagramAccountSummary {
  return {
    id: "acct_1",
    instagramUserId: "ig_1",
    username: "creator",
    graphApiVersion: "v25.0",
    linkedAt: "2026-03-01T12:00:00.000Z",
    lastSyncedAt: "2026-04-10T12:00:00.000Z",
    createdAt: "2026-03-01T12:00:00.000Z",
    updatedAt: "2026-04-10T12:00:00.000Z",
  };
}

export function makeFixtureReport(): PrecomputedAnalysisReport {
  return {
    generatedAt: "2026-04-10T12:00:00.000Z",
    analysisVersion: "v1",
    window: {
      since: "2026-03-11T12:00:00.000Z",
      until: "2026-04-10T12:00:00.000Z",
      days: 30,
    },
    accountSummary: {
      username: "creator",
      followers: 25000,
      following: 500,
      bio: "Helping builders grow with practical systems",
      website: "https://example.com",
      profilePictureUrl: "https://example.com/avatar.jpg",
    },
    posts: [
      {
        id: "post-1",
        postedAt: "2026-04-08T12:00:00.000Z",
        type: "REEL",
        caption: "ep. 6 OVERSHARING OUR FINANCES\nSave $60,000 on taxes with the right partner. #money #taxes",
        transcript:
          "If you're married to the right person, you can literally save $60,000 on taxes.",
        hook: "If you're married to the right person, you can literally save $60,000 on taxes.",
        theme: "finance",
        hashtags: ["money", "taxes"],
        views: 18000,
        reach: 14000,
        likes: 900,
        saves: 620,
        shares: 520,
        comments: 55,
        engagementRate: 0.1496,
        permalink: "https://instagram.com/p/post-1",
        thumbnailUrl: "https://example.com/post-1.jpg",
        analysisVersion: "v1",
      },
      {
        id: "post-2",
        postedAt: "2026-04-06T12:00:00.000Z",
        type: "REEL",
        caption: "ep. 7 OVERSHARING OUR FINANCES\nWhy couples should think like cofounders. #money",
        transcript:
          "If you and your partner build strategically, you can create more wealth together.",
        hook: "If you and your partner build strategically, you can create more wealth together.",
        theme: "finance",
        hashtags: ["money"],
        views: 8200,
        reach: 6100,
        likes: 340,
        saves: 210,
        shares: 180,
        comments: 19,
        engagementRate: 0.1228,
        permalink: "https://instagram.com/p/post-2",
        thumbnailUrl: "https://example.com/post-2.jpg",
        analysisVersion: "v1",
      },
      {
        id: "post-3",
        postedAt: "2026-04-04T12:00:00.000Z",
        type: "REEL",
        caption:
          "How I turned Claude into my founder coach using 5 numbers. #ai #claude #automation",
        transcript: "How I turned Claude into my founder coach using 5 numbers.",
        hook: "How I turned Claude into my founder coach using 5 numbers.",
        theme: "claude",
        hashtags: ["ai", "claude", "automation"],
        views: 3100,
        reach: 2400,
        likes: 120,
        saves: 80,
        shares: 42,
        comments: 8,
        engagementRate: 0.1042,
        permalink: "https://instagram.com/p/post-3",
        thumbnailUrl: "https://example.com/post-3.jpg",
        analysisVersion: "v1",
      },
      {
        id: "post-4",
        postedAt: "2026-04-01T12:00:00.000Z",
        type: "REEL",
        caption: "Founder burnout recovery after raising fast. <script>alert(1)</script>",
        transcript: "I burned out twice building my first company and had to rebuild my work rhythm.",
        hook: "I burned out twice building my first company and had to rebuild my work rhythm.",
        theme: "founder",
        hashtags: [],
        views: 1600,
        reach: 1200,
        likes: 60,
        saves: 25,
        shares: 12,
        comments: 4,
        engagementRate: 0.0842,
        permalink: "https://instagram.com/p/post-4",
        thumbnailUrl: "https://example.com/post-4.jpg",
        analysisVersion: "v1",
      },
    ],
    aggregates: {
      totals: {
        postCount: 4,
        views: 30900,
        reach: 23700,
        likes: 1420,
        saves: 935,
        shares: 754,
        comments: 86,
        avgEngagementRate: 0.1152,
      },
      themeAverages: [],
      topPostsByMetric: {},
      hashtags: [
        {
          hashtag: "money",
          count: 2,
        },
      ],
    },
  };
}

export function makeFixtureMediaItems(): InstagramMediaListItem[] {
  return [
    {
      id: "post-1",
      instagramAccountId: "acct_1",
      lastSyncRunId: "sync_1",
      caption: "ep. 6 OVERSHARING OUR FINANCES\nSave $60,000 on taxes with the right partner. #money #taxes",
      commentsCount: 55,
      likeCount: 900,
      mediaProductType: "REELS",
      mediaType: "VIDEO",
      mediaUrl: null,
      thumbnailUrl: "https://example.com/post-1.jpg",
      previewUrl: null,
      permalink: "https://instagram.com/p/post-1",
      shortcode: null,
      postedAt: "2026-04-08T12:00:00.000Z",
      username: "creator",
      isCommentEnabled: true,
      transcriptStatus: "completed",
      transcriptText:
        "If you're married to the right person, you can literally save $60,000 on taxes.",
      transcriptLanguage: "en",
      transcriptModel: "offline",
      transcriptClipSeconds: 31,
      transcriptError: null,
      transcriptMetadata: null,
      transcriptUpdatedAt: "2026-04-08T12:05:00.000Z",
      transcript:
        "If you're married to the right person, you can literally save $60,000 on taxes.",
      hook: "If you're married to the right person, you can literally save $60,000 on taxes.",
      theme: "finance",
      hashtags: ["money", "taxes"],
      views: 18000,
      reach: 14000,
      likes: 900,
      saves: 620,
      shares: 520,
      comments: 55,
      engagementRate: 0.1496,
      analysisVersion: "v1",
      syncedAt: "2026-04-10T12:00:00.000Z",
      createdAt: "2026-04-10T12:00:00.000Z",
      updatedAt: "2026-04-10T12:00:00.000Z",
    },
    {
      id: "post-2",
      instagramAccountId: "acct_1",
      lastSyncRunId: "sync_1",
      caption: "ep. 7 OVERSHARING OUR FINANCES\nWhy couples should think like cofounders. #money",
      commentsCount: 19,
      likeCount: 340,
      mediaProductType: "REELS",
      mediaType: "VIDEO",
      mediaUrl: null,
      thumbnailUrl: "https://example.com/post-2.jpg",
      previewUrl: null,
      permalink: "https://instagram.com/p/post-2",
      shortcode: null,
      postedAt: "2026-04-06T12:00:00.000Z",
      username: "creator",
      isCommentEnabled: true,
      transcriptStatus: "completed",
      transcriptText:
        "If you and your partner build strategically, you can create more wealth together.",
      transcriptLanguage: "en",
      transcriptModel: "offline",
      transcriptClipSeconds: 29,
      transcriptError: null,
      transcriptMetadata: null,
      transcriptUpdatedAt: "2026-04-06T12:05:00.000Z",
      transcript:
        "If you and your partner build strategically, you can create more wealth together.",
      hook: "If you and your partner build strategically, you can create more wealth together.",
      theme: "finance",
      hashtags: ["money"],
      views: 8200,
      reach: 6100,
      likes: 340,
      saves: 210,
      shares: 180,
      comments: 19,
      engagementRate: 0.1228,
      analysisVersion: "v1",
      syncedAt: "2026-04-10T12:00:00.000Z",
      createdAt: "2026-04-10T12:00:00.000Z",
      updatedAt: "2026-04-10T12:00:00.000Z",
    },
    {
      id: "post-3",
      instagramAccountId: "acct_1",
      lastSyncRunId: "sync_1",
      caption: "How I turned Claude into my founder coach using 5 numbers. #ai #claude #automation",
      commentsCount: 8,
      likeCount: 120,
      mediaProductType: "REELS",
      mediaType: "VIDEO",
      mediaUrl: null,
      thumbnailUrl: "https://example.com/post-3.jpg",
      previewUrl: null,
      permalink: "https://instagram.com/p/post-3",
      shortcode: null,
      postedAt: "2026-04-04T12:00:00.000Z",
      username: "creator",
      isCommentEnabled: true,
      transcriptStatus: "completed",
      transcriptText: "How I turned Claude into my founder coach using 5 numbers.",
      transcriptLanguage: "en",
      transcriptModel: "offline",
      transcriptClipSeconds: 22,
      transcriptError: null,
      transcriptMetadata: null,
      transcriptUpdatedAt: "2026-04-04T12:05:00.000Z",
      transcript: "How I turned Claude into my founder coach using 5 numbers.",
      hook: "How I turned Claude into my founder coach using 5 numbers.",
      theme: "claude",
      hashtags: ["ai", "claude", "automation"],
      views: 3100,
      reach: 2400,
      likes: 120,
      saves: 80,
      shares: 42,
      comments: 8,
      engagementRate: 0.1042,
      analysisVersion: "v1",
      syncedAt: "2026-04-10T12:00:00.000Z",
      createdAt: "2026-04-10T12:00:00.000Z",
      updatedAt: "2026-04-10T12:00:00.000Z",
    },
    {
      id: "post-4",
      instagramAccountId: "acct_1",
      lastSyncRunId: "sync_1",
      caption: "Founder burnout recovery after raising fast. <script>alert(1)</script>",
      commentsCount: 4,
      likeCount: 60,
      mediaProductType: "REELS",
      mediaType: "VIDEO",
      mediaUrl: null,
      thumbnailUrl: "https://example.com/post-4.jpg",
      previewUrl: null,
      permalink: "https://instagram.com/p/post-4",
      shortcode: null,
      postedAt: "2026-04-01T12:00:00.000Z",
      username: "creator",
      isCommentEnabled: true,
      transcriptStatus: "completed",
      transcriptText: "I burned out twice building my first company and had to rebuild my work rhythm.",
      transcriptLanguage: "en",
      transcriptModel: "offline",
      transcriptClipSeconds: 26,
      transcriptError: null,
      transcriptMetadata: null,
      transcriptUpdatedAt: "2026-04-01T12:05:00.000Z",
      transcript: "I burned out twice building my first company and had to rebuild my work rhythm.",
      hook: "I burned out twice building my first company and had to rebuild my work rhythm.",
      theme: "founder",
      hashtags: [],
      views: 1600,
      reach: 1200,
      likes: 60,
      saves: 25,
      shares: 12,
      comments: 4,
      engagementRate: 0.0842,
      analysisVersion: "v1",
      syncedAt: "2026-04-10T12:00:00.000Z",
      createdAt: "2026-04-10T12:00:00.000Z",
      updatedAt: "2026-04-10T12:00:00.000Z",
    },
  ];
}

export function makeFixtureReportResponse(): ReportResponse {
  return {
    status: "ready",
    account: makeFixtureAccount(),
    latestSyncRun: null,
    report: makeFixtureReport(),
  };
}
